---
- name: Show versions
  ansible.builtin.debug:
    msg:
      - "rclone_current_version.nomad_cni_plugins_current_version => {{ nomad_cni_plugins_current_version.stdout | default('none') }}"
      - "nomad_cni_plugins_version => {{ nomad_cni_plugins_version }}"

- name: create directory
  ansible.builtin.file:
    path: "{{ nomad_cni_plugins_install_path }}"
    state: directory
    mode: "0775"

- name: download cni plugins
  ansible.builtin.get_url:
    url: "{{ nomad_cni_plugins_download_url }}"
    dest: "/tmp/cni_plugin.tgz"
    mode: "0644"
  register: _cni_plugins_download_archive
  until: _cni_plugins_download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: unpack cni plugins
  ansible.builtin.unarchive:
    src: "/tmp/cni_plugin.tgz"
    dest: "{{ nomad_cni_plugins_install_path }}"
    remote_src: true

- name: update version file
  ansible.builtin.copy:
    content: "{{ nomad_cni_plugins_version }}"
    dest: "{{ nomad_cni_plugins_install_path }}/version"
    mode: "0600"
